apps/civil_servant/urls.py
from django.urls import path

from ..civil_servant.views import (
	HomeCivilServantTemplateView,
	CivilServantCreateView,
	CivilServantListView,
	CivilServantDeleteView,
	RegisterUserCreateView
)

app_name = 'civil_servant'

urlpatterns = [
	path('', HomeCivilServantTemplateView.as_view(), name='home'),
	path('listar/', CivilServantListView.as_view(), name='listar'),
	path('crear/', CivilServantCreateView.as_view(), name='crear'),
	path('eliminar/<slug>/', CivilServantDeleteView.as_view(), name='eliminar'),
	path('register/', RegisterUserCreateView.as_view(), name='register-user'),
]

apps/entity/urls.py
from django.urls import path

from .views import EntityListView, EntityCreateView, EntityDeleteView

app_name = 'entity'

urlpatterns = [
	path('crear/', EntityCreateView.as_view(), name='crear'),
	path('listar/', EntityListView.as_view(), name='listar'),
	path('eliminar/<slug>/', EntityDeleteView.as_view(), name='eliminar'),
]

apps/formality/urls.py
from django.urls import path

from ..formality.views import (
	FormalityListView,
	FormalityCreateView,
	FormalityDeleteView,
)

app_name = 'formality'

urlpatterns = [
	path('crear/', FormalityCreateView.as_view(), name='crear'),
	path('listar/', FormalityListView.as_view(), name='listar'),
	path('eliminar/<slug>/', FormalityDeleteView.as_view(), name='eliminar'),
]

tramite/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from apps.api.router import routes
from apps.civil_servant.views import HomeAnonymousUserTemplateView

handler404 = 'apps.core.view_errors.page_not_found_view'
handler500 = 'apps.core.view_errors.server_error_view'

urlpatterns = [
	path('', HomeAnonymousUserTemplateView.as_view(), name='index'),
	path('login/', LoginView.as_view(template_name='login.html'),
	     name='login'),
	path('logout/', LogoutView.as_view(), name='logout'),
	path('admin/', admin.site.urls),
	path('funcionarios/', include('apps.civil_servant.urls')),
	path('entidades/', include('apps.entity.urls')),
	path('tramites/', include('apps.formality.urls')),
	path('api/', include(routes.urls)),
] + (static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

templates/inclusions/footer.html
{% load static %}
<style>
    .sponsors {
        display: flex;
        flex-wrap: wrap;
        flex-direction: row;
        justify-content: center;
        align-content: center;
        align-items: normal;
        padding: 0;
    }

    .sponsors li {
        padding: .5em .5em;
        display: inline-flex;
        justify-content: space-between;
        align-content: center;
        align-items: center;
        list-style: none;
    }

    .sponsors img {
        width: 200px;
    }
</style>
<footer class="main--footer main--footer-light">
    <ul class="sponsors">
        <li>
            <a href="http://es.presidencia.gov.co/" target="_blank">
                <img src="{% static 'assets/img/sponsors/gobierno_colombia.png' %}"
                     alt="gobierno_colombia">
            </a>
        </li>
        <li>
            <a href="https://observatorioplanificacion.cepal.org/" target="_blank">
                <img src="{% static 'assets/img/sponsors/todos_por_un_nuevo_pais.png' %}"
                     alt="todos_por_un_nuevo_pais">
            </a>
        </li>
        <li>
            <a href="https://www.mintic.gov.co" target="_blank">
                <img src="{% static 'assets/img/sponsors/mintic.png' %}"
                     alt="mintic">
            </a>
        </li>
        <li>
            <a href="https://www.mineducacion.gov.co/" target="_blank">
                <img src="{% static 'assets/img/sponsors/mineducacion.png' %}"
                     alt="mineducacion">
            </a>
        </li>
        <li>
            <a href="http://estrategia.gobiernoenlinea.gov.co/" target="_blank">
                <img src="{% static 'assets/img/sponsors/gobierno_digital.png' %}"
                     alt="gobierno_digital">
            </a>
        </li>
    </ul>
    <p class="text-center">
        Copyright &copy; Tramitapp. All Rights
        Reserved.</p>
</footer>

templates/inclusions/head.html
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Tu Trámite</title>
    <meta name="author" content="Tu Trámite">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <link rel="icon" href="{% static 'assets/img/favicon.ico' %}"
          type="image/png">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700%7CMontserrat:400,500">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet"
          href="{% static 'assets/css/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/jquery-ui.min.css' %}">
    <link rel="stylesheet"
          href="{% static 'assets/css/perfect-scrollbar.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/morris.min.css' %}">
    <link rel="stylesheet"
          href="{% static 'assets/css/weather-icons.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/datatables.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/sweetalert.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/sweetalert-overrides.css' %}">
</head>

templates/inclusions/headers.html
<!DOCTYPE html>
{% load static %}
<html lang="en" class="no-outlines">
{% include 'inclusions/head.html' %}
<body>
<div class="wrapper">
    <header class="navbar navbar-fixed">
        <div class="navbar--header">
            <a href="{% url 'civil_servant:home' %}"
               class="logo text-center">
                <img
                        style="width: 70px"
                        src="{% static 'assets/img/logo.png' %}"
                        alt="logo_tramitapp">
            </a> <a href="#"
                    class="navbar--btn"
                    data-toggle="sidebar"
                    title="Toggle Sidebar">
            <i class="fa fa-bars"></i> </a></div>
        <a href="#" class="navbar--btn" data-toggle="sidebar"
           title="Toggle Sidebar"> <i class="fa fa-bars"></i> </a>
        <div class="navbar--nav ml-auto">
            <ul class="nav">
                <li class="nav-item dropdown nav--user online">
                    <a href="#"
                       class="nav-link"
                       data-toggle="dropdown">
                        {% if user.avatar %}
                            <img src="{{ user.avatar }}"
                             alt=""
                             class="rounded-circle">
                        {% else %}
                            <img src="{% static 'assets/img/avatars/avatar-default.png' %}"
                             alt="avatar_usuario"
                             class="rounded-circle">
                        {% endif %}
                        <span>{{ user.get_full_name }}</span>
                        <i
                                class="fa fa-angle-down"></i> </a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'logout' %}"><i
                                class="fa fa-power-off"></i>Salir</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </header>

templates/inclusions/javascript-resources.html
{% load static %}
<script src="{% static 'assets/js/jquery.min.js' %}"></script>
<script src="{% static 'assets/js/jquery-ui.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/js/perfect-scrollbar.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.sparkline.min.js' %}"></script>
<script src="{% static 'assets/js/raphael.min.js' %}"></script>
<script src="{% static 'assets/js/morris.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.validate.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.steps.min.js' %}"></script>
<script src="{% static 'assets/js/rangeSlider.min.js' %}"></script>
<script src="{% static 'assets/js/datatables.min.js' %}"></script>
<script src="{% static 'assets/js/sweetalert.min.js' %}"></script>
<script src="{% static 'assets/js/Chart.min.js' %}"></script>
<script src="{% static 'assets/js/main.js' %}"></script>
<script src="{% static 'assets/js/sweetalert-init.js' %}"></script>

templates/inclusions/navigation.html
<div class="sidebar--nav">
    <ul>
        {% if user.is_superuser %}
            <li class="active">
                <a href="#">Entidades</a>
                <ul>
                    <li>
                        <a href="{% url 'entity:crear' %}">
                            <i class="fa fa-save"></i>
                            <span>Crear</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'entity:listar' %}">
                            <i class="fa fa-tasks"></i>
                            <span>Listar</span>
                        </a>
                    </li>
                </ul>
            </li>
        {% endif %}
        <li><a href="#">Funcionarios</a>
            <ul>
                <li>
                    <a href="{% url 'civil_servant:crear' %}">
                        <i class="fa fa-save"></i>
                        <span>Crear</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'civil_servant:listar' %}"> <i
                            class="fa fa-tasks"></i>
                        <span>Listar</span>
                    </a>
                </li>
            </ul>
        </li>
        <li><a href="#">Trámites</a>
            <ul>
                <li>
                    <a href="{% url 'formality:crear' %}">
                        <i class="fa fa-save"></i>
                        <span>Crear</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'formality:listar' %}"> <i
                            class="fa fa-tasks"></i>
                        <span>Listar</span>
                    </a>
                </li>
            </ul>
        </li>
    </ul>
</div>