apps/civil_servant/urls.py
from django.urls import path

from ..civil_servant.views import (
	HomeCivilServantTemplateView,
	CivilServantCreateView,
	CivilServantListView,
	CivilServantDeleteView,
	RegisterUserCreateView
)

app_name = 'civil_servant'

urlpatterns = [
	path('', HomeCivilServantTemplateView.as_view(), name='home'),
	path('listar/', CivilServantListView.as_view(), name='listar'),
	path('crear/', CivilServantCreateView.as_view(), name='crear'),
	path('eliminar/<slug>/', CivilServantDeleteView.as_view(), name='eliminar'),
	path('register/', RegisterUserCreateView.as_view(), name='register-user'),
]

tramite/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from apps.api.router import routes
from apps.civil_servant.views import HomeAnonymousUserTemplateView

handler404 = 'apps.core.view_errors.page_not_found_view'
handler500 = 'apps.core.view_errors.server_error_view'

urlpatterns = [
	path('', HomeAnonymousUserTemplateView.as_view(), name='index'),
	path('login/', LoginView.as_view(template_name='login.html'),
	     name='login'),
	path('logout/', LogoutView.as_view(), name='logout'),
	path('admin/', admin.site.urls),
	path('funcionarios/', include('apps.civil_servant.urls')),
	path('entidades/', include('apps.entity.urls')),
	path('tramites/', include('apps.formality.urls')),
	path('api/', include(routes.urls)),
] + (static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

templates/base.html
{% include 'inclusions/headers.html' %}
{% load static %}

<aside class="sidebar" data-trigger="scrollbar">
    <div class="sidebar--profile">
        <div class="profile--img">
            <a href="{% url 'civil_servant:home' %}">
                {% if user.avatar %}
                    <img src="{{ user.avatar }}"
                         alt="avatar_usuario"
                         class="rounded-circle">
                {% else %}
                    <img src="{% static 'assets/img/avatars/avatar-default.png' %}"
                         alt="avatar_usuario"
                         class="rounded-circle">
                {% endif %}
            </a>
        </div>
        <div class="profile--name">
            <a href="#" class="btn-link">{{ user.get_full_name }}</a></div>
        <div class="profile--nav">
            <ul class="nav">
                <li class="nav-item">
                    <a href="{% url 'logout' %}" class="nav-link"
                       title="Logout"> <i class="fa fa-sign-out-alt"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    {% include 'inclusions/navigation.html' %}
</aside>
<main class="main--container">
    {% block content %}
        <section class="main--content">
            <div class="row gutter-20">
                <div class="col-md-4 col-xs-12">
                    <div class="panel">
                        <div class="miniStats--panel text-white bg-blue">
                            <div class="miniStats--header" data-overlay="0.1">
                                <p class="miniStats--chart"
                                   data-trigger="sparkline" data-type="bar"
                                   data-width="4" data-height="30"
                                   data-color="#fff">
                                    5,6,9,4,9,5,3,5,9,15,3,2,2,3,9,11,9,7,20,9,7,6</p>
                            </div>
                            <div class="miniStats--body"><i
                                    class="miniStats--icon fa fa-address-card text-white"></i>
                                <h3 class="miniStats--title h4
                                text-white">Trámites</h3>
                                <p class="miniStats--num">{{ total_formalities }}</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-xs-12">
                    <div class="panel">
                        <div class="miniStats--panel text-white bg-orange">
                            <div class="miniStats--header" data-overlay="0.1">
                                <p class="miniStats--chart"
                                   data-trigger="sparkline" data-type="bar"
                                   data-width="4" data-height="30"
                                   data-color="#fff">
                                    2,2,3,9,11,9,7,20,9,7,6,5,6,9,4,9,5,3,5,9,15,3</p>
                            </div>
                            <div class="miniStats--body"><i
                                    class="miniStats--icon fa fa-building
                                    text-white"></i>
                                <h3 class="miniStats--title h4 text-white">
                                    Entidades</h3>
                                <p class="miniStats--num">{{ total_entities }}</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-xs-12">
                    <div class="panel">
                        <div class="miniStats--panel text-white bg-green">
                            <div class="miniStats--header" data-overlay="0.1">
                                <p class="miniStats--chart"
                                   data-trigger="sparkline" data-type="bar"
                                   data-width="4" data-height="30"
                                   data-color="#fff">
                                    2,2,3,9,11,9,7,20,9,7,6,5,6,9,4,9,5,3,5,9,15,3</p>
                            </div>
                            <div class="miniStats--body"><i
                                    class="miniStats--icon fa fa-user
                                    text-white"></i>
                                <h3 class="miniStats--title h4 text-white">
                                    Funcionarios</h3>
                                <p class="miniStats--num">{{ total_civil_servant }}</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="panel">
                        <div class="panel-heading"><h3 class="panel-title">
                            Solicitudes de Trámites</h3>
                        </div>
                        <div class="panel-chart col-12">
                            <div id="oficial-chart">
                                <canvas id="total-formalities"></canvas>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="panel">
                        <div class="panel-heading">
                            <h3 class="panel-title">Trámites más visitados</h3>
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table style--2">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Nombre</th>
                                        <th>F. Realización</th>
                                        <th>Funcionario</th>
                                        <th>Horario</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for formality in formalities_recients %}
                                        <tr>
                                            <td>{{ forloop.counter }}</td>
                                            <td class="text-justify"
                                            >{{ formality.name }}</td>
                                            <td class="text-justify"
                                            >{{ formality.realization_form }}</td>
                                            <td>{{ formality.civil_servant }}</td>
                                            <td>{{ formality.schedule }}</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    {% endblock %}
    {% include 'inclusions/footer.html' %}
</main>
{% include 'inclusions/javascript-resources.html' %}
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html dir="ltr" lang="en" class="no-outlines">
{% load static %}
{% include 'inclusions/head.html' %}
<body>
<div class="wrapper">
    <div class="m-account-w" data-bg-img="assets/img/account/wrapper-bg.jpg">
        <div class="m-account">
            <div class="row no-gutters">
                <div class="col-md-6">
                    <div class="m-account--content-w"
                         data-bg-img="assets/img/account/content-bg.jpg">
                        <div class="m-account--content"><h2 class="h2">No
                            tienes una cuenta
                            ?</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur
                                adipisicing elit.</p>
                            <a href="{% url 'civil_servant:register-user' %}"
                               class="btn btn-rounded">
                                Registrarse Ahora</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="m-account--form-w">
                        <div class="m-account--form">
                            <div class="logo"><img
                                    src="{% static 'assets/img/logo.png' %}"
                                    alt=""></div>
                            <form method="post">
                                {% csrf_token %}
                                <label
                                        class="m-account--title">Ingresa a
                                    tu cuenta</label>
                                {% if form.non_field_errors %}
                                    {% for error in form.non_field_errors %}
                                        <div class="alert alert-danger">
                                            {{ error }}
                                        </div>
                                    {% endfor %}
                                {% endif %}
                                <div class="form-group">
                                    <div class="input-group">
                                        <div class="input-group-prepend"><i
                                                class="fas fa-user"></i></div>
                                        <input type="text" name="username"
                                               placeholder="Username"
                                               class="form-control"
                                               autocomplete="off" required>
                                        <span>{{ form.username.errors }}</span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="input-group">
                                        <div class="input-group-prepend"><i
                                                class="fas fa-key"></i></div>
                                        <input type="password" name="password"
                                               placeholder="Password"
                                               class="form-control"
                                               autocomplete="off" required>
                                        <span>{{ form.password.errors }}</span>
                                    </div>
                                </div>
                                <div class="m-account--actions"><a href="#"
                                                                   class="btn-link">
                                    Olvidaste tu contraseña?</a>
                                    <button type="submit"
                                            class="btn btn-rounded btn-info">
                                        Login
                                    </button>
                                </div>
                                <div class="m-account--footer"><p>&copy; 2020
                                    Tramitapp</p></div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% include 'inclusions/javascript-resources.html' %}
</body>
</html>

templates/register.html
<!DOCTYPE html>
{% load static %}
<html dir="ltr" lang="en" class="no-outlines">
{% include 'inclusions/head.html' %}
<body>
<div class="wrapper">
    <div class="m-account-w" data-bg-img="assets/img/account/wrapper-bg
    .jpg">
        <div class="m-account">
            <div class="row no-gutters flex-row-reverse">
                <div class="col-md-6">
                    <div class="m-account--content-w"
                         data-bg-img="assets/img/account/content-bg.jpg">
                        <div class="m-account--content"><h2
                                class="h2">Tengo una cuenta?</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur
                                adipisicing elit.</p><a
                                    href="{% url 'login' %}"
                                    class="btn
                                                        btn-rounded">Ingresar
                                Ahora</a></div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="m-account--form-w">
                        <div class="m-account--form">
                            <div class="logo"><img
                                    src="{% static 'assets/img/logo.png' %}"
                                    alt=""></div>
                            <form method="post">
                                {% csrf_token %}
                                <label class="m-account--title">Crea tu
                                    cuenta</label>
                                {% include 'inclusion_tags/success-message.html' %}
                                <div class="form-group">
                                    <div class="input-group">
                                        <div class="input-group-prepend"><i
                                                class="fas fa-user"></i></div>
                                        <input type="text" name="username"
                                               placeholder="Username"
                                               class="form-control"
                                               autocomplete="off" required>
                                        <span>{{ form.username.errors }}</span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="input-group">
                                        <div class="input-group-prepend"><i
                                                class="fas fa-envelope"></i>
                                        </div>
                                        <input type="email" name="email"
                                               placeholder="Email"
                                               class="form-control"
                                               autocomplete="off" required>
                                        <span>{{ form.email.errors }}</span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="input-group">
                                        <div class="input-group-prepend"><i
                                                class="fas fa-key"></i></div>
                                        <input type="password" name="password"
                                               placeholder="Password"
                                               class="form-control"
                                               autocomplete="off" required>
                                    </div>
                                </div>
                                <div class="m-account--actions">
                                    <button type="submit"
                                            class="btn btn-block btn-rounded btn-info">
                                        Registrar
                                    </button>
                                </div>
                                <div class="m-account--footer"><p>&copy; 2020
                                    Tramitapp</p></div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% include 'inclusions/javascript-resources.html' %}
</body>
</html>